import { CHANGE_CHESS, CHANGE_INIT } from '../actionType/ChessActionType';

const chessInit = {
  chessMap: [
    [
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ],
      [
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null },
        { stepNumber: null, xIsNext: null }
      ]
    ]
  ],
  stepNumber: 0, //步数
  xIsNext: true, //执棋手true为白棋false为黑棋
  earlyOrLate: false, //先攻||后攻
  flag: true, //true为完成对局||还未开始||暂停false为游戏进行中
  king: null //最后的赢家是
};

export default function ChessReducer(state = chessInit, action) {
  switch (action.type) {
    case CHANGE_CHESS:
      return { ...state, ...action.payload };
    case CHANGE_INIT:
      return { ...state };
    default:
      return state;
  }
}
